###
GET http://localhost:8090/operations

###
GET http://localhost:8090/operations/9cbed0d7-a79c-46bd-847f-d85bd509fb91

###
POST http://localhost:8090/operations
Content-Type: application/json

{
  "label": "Achat DVD SNK",
  "amount": 25.26,
  "secondAccountName": "FNAC",
  "secondAccountCountry" : "England",
  "secondAccountIBAN": "EN9930001007941234567890185",
  "firstAccountId": "5d707d00-945f-4c7c-ba02-e80ce826a2ad"
}

###
PUT http://localhost:8090/operations/9cbed0d7-a79c-46bd-847f-d85bd509fb91
Content-Type: application/json

{
  "label": "Achat DVD SNK",
  "amount": 45.26,
  "secondAccountName": "FNAC",
  "secondAccountCountry" : "England",
  "secondAccountIBAN": "EN9930001007941234567890185",
  "firstAccountId": "5d707d00-945f-4c7c-ba02-e80ce826a2ad"
}

###
PATCH http://localhost:8090/operations/9cbed0d7-a79c-46bd-847f-d85bd509fb91
Content-Type: application/json

{
  "label": "Achat DVD SNK",
  "amount": 45.26,
  "secondAccountName": "FNAC",
  "secondAccountCountry" : "England",
  "secondAccountIBAN": "EN9930001007941234567890185",
  "firstAccountId": "5d707d00-945f-4c7c-ba02-e80ce826a2ad"
}

###
PATCH http://localhost:8090/operations/9cbed0d7-a79c-46bd-847f-d85bd509fb91
Content-Type: application/json

{
  "category": "achat du quotidien"
}

###
DELETE http://localhost:8090/operations/9cbed0d7-a79c-46bd-847f-d85bd509fb91

###
POST http://localhost:8090/operations/9cbed0d7-a79c-46bd-847f-d85bd509fb91/confirm